# Generated by Django 5.1.3 on 2025-01-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birtdate',
            field=models.DateField(default='1999-01-01', verbose_name='Birthdate'),
        ),
    ]
