# Generated by Django 5.1.3 on 2025-01-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_userprofile_birtdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Is Approved'),
        ),
    ]
