# Generated by Django 5.1.3 on 2025-01-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_userprofile_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birtdate',
            new_name='birthdate',
        ),
    ]
