# Generated by Django 5.1.3 on 2025-01-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_patientdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientData',
        ),
    ]
