# Generated by Django 5.1.3 on 2025-02-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_userprofile_certeficate_serial_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='certeficate_serial',
            new_name='certificate_serial',
        ),
    ]
