# Generated by Django 5.1.3 on 2025-02-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_alter_otp_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_file', models.FileField(upload_to='diplomas/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_diplomas', to='user_auth.userprofile')),
            ],
        ),
    ]
