# Generated by Django 5.1.3 on 2025-02-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_additionaldiploma'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='main_diploma',
            field=models.FileField(blank=True, null=True, upload_to='main_diplomas/'),
        ),
    ]
