# Generated by Django 5.1.3 on 2025-01-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='views',
        ),
    ]
