# Generated by Django 5.1.3 on 2025-02-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_patientdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientData',
        ),
    ]
