# Generated by Django 5.1.3 on 2025-03-03 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DIABETES', 'Diabetes'), ('OBESITY', 'Obesity')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(600.0)])),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('bmi_value', models.FloatField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bmi_records', to=settings.AUTH_USER_MODEL)),
                ('sickness', models.ManyToManyField(to='patient.illness')),
            ],
            options={
                'verbose_name': 'BMI Record',
                'verbose_name_plural': 'BMI Records',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_type', models.CharField(choices=[('mg/dl', 'mg/dl'), ('mmol/l', 'mmol/l')], max_length=10)),
                ('fasting_glucose', models.FloatField()),
                ('hba1c', models.FloatField()),
                ('cholesterol', models.IntegerField()),
                ('bmi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes', to='patient.bmi')),
            ],
            options={
                'verbose_name': 'Diabetes Record',
                'verbose_name_plural': 'Diabetes Records',
            },
        ),
        migrations.CreateModel(
            name='Obesity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.FloatField()),
                ('hdl', models.FloatField()),
                ('ldl', models.FloatField()),
                ('triglycerides', models.FloatField()),
                ('cholesterol', models.IntegerField()),
                ('ac_uric', models.IntegerField()),
                ('bmi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='obesity', to='patient.bmi')),
            ],
            options={
                'verbose_name': 'Obesity Record',
                'verbose_name_plural': 'Obesity Records',
            },
        ),
    ]
