# Generated by Django 5.1.3 on 2025-03-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrequest',
            name='update_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVISED', 'REVISED'), ('NONE', 'NONE')], default='NONE', max_length=20),
        ),
    ]
