# Generated by Django 5.1.3 on 2025-03-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_dietrequest_update_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietrequest',
            name='request_verified',
        ),
    ]
