# Generated by Django 5.1.3 on 2025-03-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='is_analyzed',
            new_name='request_verified',
        ),
    ]
