# Generated by Django 5.1.3 on 2025-04-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_dietrequest_request_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietrequest',
            old_name='alcohol',
            new_name='weight_loss',
        ),
    ]
