# Generated by Django 5.1.3 on 2025-06-16 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_alcohol_dietrequest_weight_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrequest',
            name='last_meal_time',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Enter time in either 24-hour (HH:MM) or 12-hour (HH:MM AM/PM) format', regex='^([0-1]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?$|^([0-1]?[0-9]|2[0-3]):[0-5][0-9](:[0-5][0-9])?\\s?(AM|PM|am|pm)$')]),
        ),
    ]
