# Generated by Django 5.1.3 on 2025-03-04 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_is_analyzed_patientprofile_request_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_verified', models.BooleanField(default=False)),
                ('bmi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.bmi')),
                ('diabetes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.diabetes')),
                ('obesity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.obesity')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
