# Generated by Django 5.1.3 on 2025-03-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_dietrequest_delete_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrequest',
            name='diabetes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.diabetes'),
        ),
        migrations.AlterField(
            model_name='dietrequest',
            name='obesity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.obesity'),
        ),
    ]
