# Generated by Django 5.1.3 on 2025-03-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_dietrequest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrequest',
            name='between_meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='meals_per_day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Once a day'), (2, 'Twice a day'), (3, 'Three times a day'), (4, 'Four times a day')], default=1),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='sweets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='update_status',
            field=models.CharField(choices=[('PENDING', 'Pending Update'), ('UPDATED', 'Successfully Updated'), ('NONE', 'No Update Needed')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(choices=[('DIABETES', 'Diabetes'), ('OBESITY', 'Obesity'), ('DIABETESANDOBESITY', 'Obesity')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='DiabetesAndObesity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.FloatField()),
                ('hb1ac', models.FloatField()),
                ('hdl', models.FloatField()),
                ('ldl', models.FloatField()),
                ('triglycerides', models.FloatField()),
                ('cholesterol', models.IntegerField()),
                ('ac_uric', models.IntegerField()),
                ('fns', models.FloatField()),
                ('crp', models.FloatField()),
                ('vitamin_d', models.FloatField()),
                ('b12', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('bmi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_and_obesity', to='patient.bmi')),
            ],
            options={
                'verbose_name': 'Diabetes and Obesity Record',
                'verbose_name_plural': 'Diabetes and Obesity Records',
            },
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='diabetes_and_obesity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.diabetesandobesity'),
        ),
    ]
