# Generated by Django 5.1.3 on 2025-03-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_dietrequest_between_meals_dietrequest_meals_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(choices=[('DIABETES', 'Diabetes'), ('OBESITY', 'Obesity'), ('DIABETESANDOBESITY', 'DIABETESANDOBESITY')], max_length=20, unique=True),
        ),
    ]
