# Generated by Django 5.1.3 on 2025-03-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_illness_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(choices=[('DIABETES', 'Diabetes'), ('OBESITY', 'Obesity'), ('DIABETESANDOBESITY', 'diabetesandobesity')], max_length=20, unique=True),
        ),
    ]
