# Generated by Django 5.1.3 on 2025-03-14 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_illness_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietrequest',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='allergy_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='depression_stress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='enough_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='fast_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='food_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='last_meal_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='medication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='medication_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='sleep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dietrequest',
            name='walking',
            field=models.BooleanField(default=False),
        ),
    ]
