# Generated by Django 5.1.3 on 2025-03-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_dietrequest_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('diet_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to='patient.dietrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=3)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='doctor.diet')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACK', 'Snack'), ('DINNER', 'Dinner')], max_length=9)),
                ('description', models.TextField()),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='doctor.dailymealplan')),
            ],
        ),
    ]
