# Generated by Django 5.1.3 on 2025-03-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to='patient.dietrequest'),
        ),
    ]
