# Generated by Django 5.1.3 on 2025-03-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_diet_diet_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
